#!/bin/bash

# Image optimization script
# This script will help you optimize your images manually

echo "Image Optimization Guidelines for Aurora Luxe Travel"
echo "=================================================="
echo ""
echo "Current image sizes found:"
echo "- bali.jpg: 1.9MB"
echo "- hompage-range.jpg: 1.3MB" 
echo "- maldivs.jpg: 8.2MB (!) - This is very large"
echo "- netherlands.jpg: 3.3MB"
echo "- sri-lanka.jpg: 4.4MB"
echo ""
echo "Recommended optimizations:"
echo "1. Resize images to appropriate dimensions:"
echo "   - Hero images: 1920x1080 max"
echo "   - Card images: 800x600 max"
echo "   - Thumbnails: 400x300 max"
echo ""
echo "2. Compress images:"
echo "   - Use WebP format when possible"
echo "   - Quality: 80-85% for photos"
echo "   - Target size: Under 200KB for cards, under 500KB for hero images"
echo ""
echo "3. Tools you can use:"
echo "   - Online: TinyPNG, Squoosh, Compressor.io"
echo "   - Command line: imagemagick, cwebp"
echo "   - Photoshop: Export for Web"
echo ""
echo "4. Immediate action needed:"
echo "   - Replace maldivs.jpg (8.2MB) - this is causing major loading delays"
echo "   - Optimize all images to under 500KB each"